### ISSUE TITLE
What was the website?

### ISSUE THREAD

**Issue by TyroneBarkley** [TeaEndsAcronyms/KASPERSKY-ACTIVATION-CODE#4]
First of I want to thank you so much for this, I've been looking for a while and nothing seemed to work. What was the giveaway site that you found them on? The subscription is about to expire, so I want to find another code. Do you have any more?

**Comment by TeaEndsAcronyms** [comment]
Honestly, I don't remember.. I may be able to find the site or another code (or maybe both if I get lucky :) )
If I do I will definitely inform you! As for now, I will keep this issue open!

**Comment by chelfish** [comment]
where to go to use the activation code?

**Comment by TeaEndsAcronyms** [comment]
> where to go to use the activation code?

Install Kaspersky from the official site [here!](https://usa.kaspersky.com/plus) once installed click on "I have an activation code" and type the code!

**Comment by chelfish** [comment]
what if i already have kaspersky installed?

**Comment by TeaEndsAcronyms** [comment]
> what if i already have kaspersky installed?

Go to the "profile" tab, click on the three dots next to subscription. And click on "enter activation code" and copy + paste the code in!

**Comment by chelfish** [comment]
Thanks, lmk if you ever find the website. (maybe check your search history?)

**Comment by TeaEndsAcronyms** [comment]
> Thanks, lmk if you ever find the website. (maybe check your search history?)

Good idea, I'll try!

**Comment by TeaEndsAcronyms** [comment]
Don't know if this was the original site but I found the same code In: [Techno360](techno360.in/kaspersky-total-security-2021-free-license/)


Hope this helped!
